.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "BAGATELA\-API" "1" "August 2011" "Stanisław Wasiutyński" ""
.
.SH "NAME"
\fBbagatela\-api\fR \- dane o komunikacji miejskiej od przewoźników
.
.SH "WSTĘP DO API"
API (Interfejs Programowania Aplikacji) umożliwia programowy dostęp do danych (\fIprzystanków\fR, \fIrozkładów jazdy\fR) i usług (\fIwyszukiwarka przystanków\fR) z poziomu aplikacji trzecich\.
.
.P
API jest zgodne ze wzorcem REST \fIhttp://en\.wikipedia\.org/wiki/Representational_State_Transfer\fR\. Interakcja na zbiorach odbywa się protokołem HTTP i pozwala na wykonywanie zapytań typu GET i POST\. Dane przyjmowane i zwracane są w formacie JSON \fIhttp://json\.org\fR\.
.
.SS "Url"
Każde miasto posiada swój własny adres url według wzoru:
.
.IP "" 4
.
.nf

http://api\.bagate\.la/<kod_miasta>
.
.fi
.
.IP "" 0
.
.P
Oto kody miast, których rozkłady są aktualnie gromadzone (oczekuj nowych miast):
.
.IP "" 4
.
.nf

sk \- Górnośląski Okręg Przemysłowy (od 20\.06\.2011)
kr \- Kraków (od 20\.06\.2011)
dw \- Wrocław (od 20\.06\.2011)
.
.fi
.
.IP "" 0
.
.SS "Przykłady"
Wszystkie przykłady interakcji z API korzystają z prostego narzędzia konsoli \fBcurl\fR i zostały wykonane w systemie GNU/Linux\.
.
.IP "" 4
.
.nf

curl http://api\.bagate\.la \-\-verbose
.
.fi
.
.IP "" 0
.
.IP "" 4
.
.nf

* About to connect() to api\.bagate\.la port 80 (#0)
*   Trying 31\.222\.178\.135\.\.\. connected
* Connected to api\.bagate\.la (31\.222\.178\.135) port 80 (#0)
> GET / HTTP/1\.1
> User\-Agent: curl/7\.21\.3 (x86_64\-pc\-linux\-gnu) libcurl/7\.21\.3 OpenSSL/0\.9\.8o zlib/1\.2\.3\.4 libidn/1\.18
> Host: api\.bagate\.la
> Accept: */*
>
< HTTP/1\.1 200 OK
< Content\-Type: application/json
< Connection: keep\-alive
< Status: 200
< X\-Powered\-By: Phusion Passenger (mod_rails/mod_rack) 3\.0\.7
< Content\-Length: 48
< Server: nginx/1\.0\.4 + Phusion Passenger 3\.0\.7 (mod_rails/mod_rack)
<
* Connection #0 to host api\.bagate\.la left intact
* Closing connection #0
{"message":"Welcome aboard!","version":"40f6ca"}
.
.fi
.
.IP "" 0
.
.SS "Debugging"
Flaga \fB\-\-verbose\fR wyświetla bardziej szczegółowe informacje o połączeniu\. Więcej informacji o narzędziu \fBcurl\fR znajdziesz w jego dokumentacji \fIhttp://curl\.haxx\.se/docs/manpage\.html\fR\. Przy nauce protokołu, przydatne mogą okazać się również inne \fIhttp://justniffer\.sourceforge\.net/index\.html\fR narzędzia \fIhttp://postbin\.org\fR\.
.
.SS "Kontrybucja"
(również do dokumentacji) jest mile widziana! Weź \fIhttps://github\.com/Stanley/bagatela\fR na widły i poproś o akceptacje zmian\.
.
.SH "ZAPYTANIA O DANE"
Ponieważ dane są przechowywane w bazie danych CouchDB, która udostępnia interfejs REST, nasz interfejs programistyczny jest z nim całkowicie zgodny\. Jego szczegóły opisano w dokumentacji CouchDB API \fIhttp://wiki\.apache\.org/couchdb/\fR\.
.
.SS "Dokumenty"
Dokument jest podstawową strukturą organizacji danych w bazie\. Motywacją użycia takiej jednostki jest łatwość przenoszenia rzeczywistych obiektów (takich jak rozkłady jazdy) do postaci zrozumiałej dla komputera\. Dokumenty są ograniczone, nie sztywną strukturą, a jedynie tym, że składają się z tablicy dowolnej ilości par, w których kluczem jest napis, a wartością dana o jedym z typów: binarny, napis, liczba, tablica, tablica asocjacyjna lub niezdefiniowany\. W bazie danych dokumenty są przechowywane w formacie JSON i w tej samej formie są zwracane na zewnątrz\.
.
.P
Każdy dokument posiada unikalny identyfikator \fB_id\fR oraz numer rewizji \fB_rev\fR\. Atrybuty te są nadawane automatycznie przez bazę danych\. Aby otrzymać pojedynczy dokument, (prawie zawsze) wystarczy przekazać jedynie identyfikator \fB_id\fR\. Np\.:
.
.IP "" 4
.
.nf

http://api\.bagate\.la/kr/d778919c8c13d6dfc59d8a4fbcffa409
.
.fi
.
.IP "" 0
.
.P
Ścieżka: \fB/<id>\fR
.
.br
Metoda: \fBGET\fR
.
.br
Parametry: \fBid\fR, \fBrev\fR (opcjonalnie) \- numer rewizji
.
.br
Odpowiedź: dokument o identyfikatorze \fBid\fR (domyślnie najnowsza rewizja)\.
.
.P
Przykładowe użycie:
.
.IP "" 4
.
.nf

curl \-XGET http://api\.bagate\.la/kr/d778919c8c13d6dfc59d8a4fbcffa409
.
.fi
.
.IP "" 0
.
.IP "" 4
.
.nf

{
  "_id":"d778919c8c13d6dfc59d8a4fbcffa409",
  "_rev":"3\-c7ea32524b4fb94e66d7214a2eb62427",
  "type":"Stop",
  "updated_at":"2011\-06\-24T08:47:04Z",
  "name":"Agatowa",
  "location":{
    "lat":50\.02198398,
    "lon":20\.04249077
  }
}
.
.fi
.
.IP "" 0
.
.P
Przeczytaj więcej o dokumentach w CouchDB na: \fIhttp://guide\.couchdb\.org/editions/1/en/api\.html#documents\fR\.
.
.SS "Zasoby"
Zasób jest podzbiorem danych w bazie, wydzielonych względem typu (klasy) danej, którą reprezentuje\. Typ zasobu do którego należy dokument jest określony w polu \fBtype\fR\.
.
.SS "Widoki"
Widok to predefiniowany indeks danych\. Definicja widoku jest w bazie danych specjalnym dokumentem i zawiera funkcje: mapującą i opcjonalnie redukującą\. Funkcje przetwarzają każdy dokument z osobna i zapisują wynik w posortowanej liście (widoku)\. Istnieją dwa rodzaje wyszukań tego indeksu: o dokumenty z danym kluczem i o dokumenty z kluczami mieszczącymi się w danym zakresie\. Jeżeli znamy konkretny klucz i dodamy go ścieżki widoku w parametrze \fBkey\fR, to w rezultacie otrzymamy wartość wygenerowaną przez dokument (jeden lub więcej, gdy klucz nie jest unikalny), będący wynikiem przetwarzania funkcją mapującą lub redukującą\.
.
.P
Częstszym użyciem widoków jest pytanie o zbiór dokumentów, których klucze są zawarte w pewnym przedziale\. Aby ułatwić takie zapytania, klucze często są wartością typu lista, np\. \fI[2010, 10, 6]\fR\. Dzięki temu jesteśmy w stanie zapytać o wszystkie dokumenty, których klucz zawiera się w danym przedziale np\. od \fI[2010, 9]\fR do \fI[2010, 10, {}]\fR (w tym przypadku, gdzie kluczem jest data, zapytanie zwróci wszystkie dokumenty z kluczem od 1 września do 30 października)\.
.
.P
Przeczytaj więcej o widokach w CouchDB na: \fIhttp://guide\.couchdb\.org/editions/1/en/views\.html\fR\.
.
.P
Ścieżka: \fB/_design/<zasób>/_view/<widok>\fR
.
.br
Metoda: \fBGET\fR
.
.br
Parametry:
.
.IP "\(bu" 4
\fBdescending\fR \- jeżeli \fItrue\fR, odwrócona kolejność zwracanych dokumentów\. Uwaga: sortowanie odbywa się przed ograniczeniem przedziału\. Może to oznaczać konieczność zamiany parametrów \fBstartkey\fR z \fBendkey\fR\.
.
.IP "\(bu" 4
\fBendkey\fR \- koniec przedziału włącznie\. Domyślnie największa możliwa wartość\.
.
.IP "\(bu" 4
\fBendkey_docid\fR \- identyfikator ostatniego dokumentu w odpowiedzi (używane do paginacji)\.
.
.IP "\(bu" 4
\fBgroup\fR \- jeżeli \fIfalse\fR to redukuje wszystkie dokumenty zgodnie z funkcją redukującą do jednej wartości\. W przeciwnym wypadku wyniki przetwarzania każdego z dokumentów są grupowane\. Domyślnie \fIfalse\fR\.
.
.IP "\(bu" 4
\fBgroup_level\fR \- grupuje wyniki przetwarzania funkcją redukującą, mające pierwszych \fIgrup_level\fR takich samych wartości klucza\. Np\.: klucze \fI["a", "b", "c"], ["a", "b", "d"], ["a", "c", "d"]\fR z parametrem \fIgroup_level=2\fR utworzą dwie grupy \fI["a", "b"], ["a", "c"]\fR \. Jeżeli parametr \fBgroup\fR będzie \fItrue\fR a \fBgroup_level\fR niezdefiniowany, to zwrócony zostanie wynik przetwarzania każdego dokumentu z osobna\.
.
.IP "\(bu" 4
\fBinclude_docs\fR \- jeżeli \fItrue\fR, dołącza oryginalny dokument w polu \fBdoc\fR\. Domyślnie \fIfalse\fR\.
.
.IP "\(bu" 4
\fBinclusive_end\fR \- definiuje czy dokument o kluczu \fBendkey\fR jest dołączany do odpowiedzi\. Domyślnie \fItrue\fR\.
.
.IP "\(bu" 4
\fBkey\fR \- dokładna wartość klucza\.
.
.IP "\(bu" 4
\fBlimit\fR \- maksymalna liczba zwróconych dokumentów\. Np\. \fI10\fR\.
.
.IP "\(bu" 4
\fBreduce\fR \- użyj funkcji redukującej\. Domyślna wartość, gdy funkcja redukująca jest zdefiniowana, to \fItrue\fR\.
.
.IP "\(bu" 4
\fBskip\fR \- liczba pomijanych dokumentów\. Domyślnie \fI0\fR\.
.
.IP "\(bu" 4
\fBstale\fR \- definiuje czy akceptować przedawniony widok, w celu otrzymania natychmiastowej odpowiedzi (w przypadku gdy nowy widok jeszcze nie skończył się generować)\. Możliwa wartość: \fIok\fR\.
.
.IP "\(bu" 4
\fBstartkey\fR \- początek przedziału włącznie\. Domyślnie najmniejsza możliwa wartość\.
.
.IP "\(bu" 4
\fBstartkey_docid\fR \- identyfikator pierwszego dokumentu w odpowiedzi (używane do paginacji)\.
.
.IP "" 0
.
.P
Wszystkie wyżej wymienione parametry są opcjonalne\.
.
.SH "ROZKŁAD JAZDY"
Fizycznie reprezentuje wydruk z przystanku\. Jest związany z jedną linią i z jednym przystankiem\. Obowiązuje w ograniczonej ramie czasowej (choć data upływu ważności nie jest znana dopóki nie zostanie opublikowana aktualizacja rozkładu)\. Jest wiernym odzwierciedleniem tego co jest publikowane przez przewoźników na ich oficjalnych stronach i nie zawiera żadnych dodatkowych inforamcji (oprócz opcjonalnych atrybutów \fBstop_id\fR i \fBvalid_until\fR)\.
.
.SS "Atrybuty"
.
.IP "\(bu" 4
\fB_id\fR \- identyfikator\.
.
.IP "\(bu" 4
\fB_rev\fR \- numer rewizji\.
.
.IP "\(bu" 4
\fBline\fR \- numer linii, którą opisuje rozkład\. Np\. \fI"4"\fR\.
.
.IP "\(bu" 4
\fBroute\fR \- trasa linii\. Lista głównych ulic, którymi biegnie linia\. Np\. \fI"Al\. 3 Maja, Podwale, Basztowa, Lubicz, Rakowicka"\fR\.
.
.IP "\(bu" 4
\fBdestination\fR (tylko jeżeli parametr \fBroute\fR nie istnieje) \- przystanek docelowy\. Np\. \fI"Okęcie"\fR\.
.
.IP "\(bu" 4
\fBstop\fR \- nazwa przystanku na którym znajduje się rozkład\. Np\. \fI"Batorego"\fR\.
.
.IP "\(bu" 4
\fBstop_id\fR (opcjonalnie) \- identyfikator przystanku \fBStop\fR przy którym zatrzymuje się transport\.
.
.IP "\(bu" 4
\fBtable\fR \- tablice odjazdów\. Atrybut typu tablicy asocjacyjnej, przechowującej pary, w których opisowi dni odpowiada tablica odjazdów\. Opis dania (klucz) to np\. \fI"Dzień powszedni"\fR\. Tablica odjazdów (wartość) to np\. \fI{"4":["43"], "5":["02","17","38","48","58"]}\fR, co oznacza, że w dni powszednie, o godzinie 4:43, 5:02, 5:17 itd\. odjeżdża transport\. Minuty są ciągiem znaków, gdyż mogą zawierać opis kursu\. Np\. \fI"24A"\fR\.
.
.IP "\(bu" 4
\fBtype\fR \- typ\. Zawsze \fI"Timetable"\fR\.
.
.IP "\(bu" 4
\fBsource\fR \- źródło danych\. Np\. adres URL: \fI"http://rozklady\.mpk\.krakow\.pl/aktualne/0004/0004t023\.htm"\fR\.
.
.IP "\(bu" 4
\fBupdated_at\fR \- czas ostatniej modyfikacji w bazie danych (tj\. czas połączenia ze źródłem)\.
.
.IP "\(bu" 4
\fBvalid_from\fR \- dzień od którego obowiązuje rozkład\. Np\. \fI"04\.10\.2010"\fR\.
.
.IP "\(bu" 4
\fBvalid_until\fR (opcjonalnie) \- dzień do którego obowiązuje rozkład\. Jeżeli atrybut nie jest zdefiniowany i \fBvalid_from\fR wskazuje na przeszły dzień to rozkład jazdy jest aktualnie obowiązującym\. Atrybut zostanie zdefiniowany nie wcześniej, niż nowa wersja tego rozkładu zostanie publikowana lub aktualny zostanie anulowany\.
.
.IP "" 0
.
.SS "Załączniki"
.
.IP "\(bu" 4
\fBsource\.html\fR \- oryginalna strona HTML z rozkładem jazdy\.
.
.IP "" 0
.
.SS "Widoki"
Definicje funkcji mapujących, redukujących i listujących rozkłady jazdy, są dokumentem o idenyfikatorze \fI"_design/Timetables"\fR\.
.
.P
\fB[map] by_line\fR
.
.P
Ścieżka: \fB/_design/Timetables/_view/by_line?reduce=false\fR
.
.br
Metoda: \fBGET\fR
.
.br
Odpowiedź: lista rozkładów jazdy
.
.br
Kolejność sortowania: \fBline\fR, \fBdestination\fR, \fBsource\fR
.
.P
Przykładowe użycie:
.
.IP "" 4
.
.nf

curl \-XGET http://api\.bagate\.la/kr/_design/Timetables/_view/by_line?startkey=["6","SALWATOR"]&endkey=["6","SALWATOR",{}]&reduce=false
.
.fi
.
.IP "" 0
.
.P
Zwraca listę rozkładów na linii numer \fI"6"\fR, jadącej w kierunku przystanku \fI"Salwator"\fR, posortowanych od pierwszego do ostatniego\.
.
.P
\fB[reduce] by_line\fR
.
.P
Jeżeli interesuje nas opis danej lini (będący skrótem informacji z wielu rozkładów jazdy), musimy skorzystać z widoku wygenerowanego funkcją redukującą\.
.
.P
Ścieżka: \fB/_design/Timetables/_view/by_line\fR
.
.br
Metoda: \fBGET\fR
.
.br
Odpowiedź: liczba dokumentów w danej grupie
.
.P
Przykładowe użycia:
.
.IP "" 4
.
.nf

curl \-XGET http://api\.bagate\.la/kr/_design/Timetables/_view/by_line?startkey=["113","ALEJA PRZYJAŹNI"]&endkey=["113","ALEJA PRZYJAŹNI",{}]&group_level=2
.
.fi
.
.IP "" 0
.
.P
Zwraca liczbę przystanków na linii \fI113\fR w kierunku przystanku \fIAleja Przyjaźni\fR\.
.
.IP "" 4
.
.nf

curl \-XGET http://api\.bagate\.la/kr/_design/Timetables/_view/by_line?group_level=1
.
.fi
.
.IP "" 0
.
.P
Zwraca liczbę przystanków na wszystkich liniach o tym samym numerze (tam i z powrotem)\. Zapytanie jest również przydatne, gdy chcemy uzyskać listę numerów linii (które w zwróconym rezultacie są kluczem; parametr \fBkey\fR)\. Należy pamiętać, że numery linii są ciągami znaków, a nie liczb, dlatego linia \fI"10"\fR pojawi się przed \fI"2"\fR\.
.
.P
\fB[map] by_source\fR
.
.P
Ścieżka: \fB/_design/Timetables/_view/by_source\fR
.
.br
Metoda: \fBGET\fR
.
.br
Odpowiedź: lista rozkładów jazdy
.
.br
Kolejność sortowania: \fBsource\fR, \fBvalid_from\fR
.
.P
Przykładowe użycie\.
.
.IP "" 4
.
.nf

curl \-XGET http://api\.bagate\.la/kr/_design/Timetables/_view/by_source?startkey=["http://rozklady\.mpk\.krakow\.pl/aktualne/0000/0000t001\.htm"]&limit=1
.
.fi
.
.IP "" 0
.
.P
Zwraca najnowszy rozkład jazdy pozyskany z danego źródła\.
.
.P
\fB[map] by_stop\fR
.
.P
Ścieżka: \fB/_design/Timetables/_view/by_stop\fR
.
.br
Metoda: \fBGET\fR
.
.br
Odpowiedź: lista przystanków i rozkładów jazdy
.
.br
Kolejność sortowania: \fBstop\fR, \fBline\fR, \fBdestination\fR
.
.P
Przykładowe użycie:
.
.IP "" 4
.
.nf

curl \-XGET http://api\.bagate\.la/kr/_design/Timetables/_view/by_stop?key=["Agatowa","125","ZŁOCIEŃ"]
.
.fi
.
.IP "" 0
.
.P
Zwraca rozkłady jazdy linii \fI"125"\fR, w stronę przystanku \fI"Złocień"\fR, na przystanku \fI"Agatowa"\fR\.
.
.P
\fB[map] by_stop_id\fR
.
.P
\fBUWAGA\fR: \fIten widok wymaga, aby rozkłady jazdy deklarowały konkretny przystanek na którym się znajdują w polu \fBstop_id\fR, które może być nie zdefiniowane\.\fR
.
.P
Ścieżka: \fB/_design/Timetables/_view/by_stop_id\fR
.
.br
Metoda: \fBGET\fR
.
.br
Odpowiedź: lista przystanków i rozkładów jazdy
.
.br
Kolejność sortowania przystanków: \fBid\fR
.
.br
Kolejność sortowania rozkładów: \fBline\fR
.
.P
Przykładowe użycie:
.
.IP "" 4
.
.nf

curl \-XGET http://api\.bagate\.la/kr/_design/Timetables/_view/by_stop_id?startkey=["d778919c8c13d6dfc59d8a4fbcfeeb5f"]&endkey=["d778919c8c13d6dfc59d8a4fbcfeeb5f",{}]
.
.fi
.
.IP "" 0
.
.P
Zwraca przystanek oraz wszystkie rozkłady jazdy na danym przystanku\. Aby pominąć przystanek, należy dodać parametr \fBskip=1\fR\.
.
.P
\fB[list] filter\fR
.
.P
Ścieżka: \fB/_design/Timetables/_list/filter/<widok>\fR
.
.br
Metoda: \fBGET\fR
.
.br
Parametr: \fBwidok\fR, \fIonly\fR lub \fIexcept\fR \- lista parametrów, połączonych przecinkiem, które mają (lub których nie mają) zawierać wartości zwrócone przez funckję mapującą
.
.br
Odpowiedź: to samo co zwróci widok, z filtrowanymi wartościami
.
.P
Przykładowe użycie:
.
.IP "" 4
.
.nf

curl \-XGET http://api\.bagate\.la/kr/_design/Timetables/_list/filter/by_line?only=stop,table&reduce=false&limit=1
.
.fi
.
.IP "" 0
.
.P
Zwraca jeden rozkład jazdy z polami: \fBstop\fR i \fBtable\fR\.
.
.P
Zobacz scenariusze testujące \fI"_design/Timetables"\fR\. \fIhttps://github\.com/Stanley/bagatela/blob/master/features/timetables_design\.feature\fR
.
.SH "PRZYSTANEK"
Fizyczna wiata lub słup przy którym wiszą rozkłady jazdy i zatrzymują się pojazdy komunikacji\.
.
.SS "Atrybuty"
.
.IP "\(bu" 4
\fB_id\fR \- identyfikator\.
.
.IP "\(bu" 4
\fB_rev\fR \- numer rewizji\.
.
.IP "\(bu" 4
\fBaddress\fR (opcjonalnie) \- ulica przy której znajduje się przystanej\. Np\. "Karmelicka"\.
.
.IP "\(bu" 4
\fBlocation\.lat\fR \- szerokość geograficzna\. Np\. \fI50\.06309891\fR\.
.
.IP "\(bu" 4
\fBlocation\.lon\fR \- długość geograficzna\. Np\. \fI19\.9326992\fR\.
.
.IP "\(bu" 4
\fBname\fR \- nazwa przystanku\. Np\. \fI"Teatr Bagatela"\fR\.
.
.IP "\(bu" 4
\fBoperates\fR (opcjonalnie) \- lista typów pojazdów, które obsługuje przystanek\. Np\. \fI["Trams", "Buses"]\fR\.
.
.IP "\(bu" 4
\fBpolylines\fR (opcjonalnie) \- tablica asocjacyjna, gdzie kluczem jest identyfikator dowolnego przystanku, a wartością tablica współrzędnych, tworzących linię łamaną, połączenie tych dwóch przystanków\.
.
.IP "\(bu" 4
\fBtype\fR \- typ\. Zawsze \fI"Stop"\fR\.
.
.IP "\(bu" 4
\fBupdated_at\fR \- czas ostatniej modyfikacji\.
.
.IP "" 0
.
.P
Definicje funkcji mapujących, redukujących i listujących przystanki są dokumentem o idenyfikatorze \fI"_design/Stops"\fR\.
.
.SS "Widoki"
\fB[map] by_line\fR
.
.P
\fBUWAGA\fR: \fIten widok wymaga, aby rozkłady jazdy deklarowały konkretny przystanek na którym się znajdują w polu \fBstop_id\fR, które może być nie zdefiniowane\.\fR
.
.P
Ścieżka: \fB/_design/Stops/_view/by_line\fR
.
.br
Metoda: \fBGET\fR
.
.br
Odpowiedź: lista przystanków Kolejność sortowania: \fBline\fR, \fBdestination\fR, \fBsource\fR
.
.P
Przykładowe użycie:
.
.IP "" 4
.
.nf

curl \-XGET http://api\.bagate\.la/kr/_design/Stops/_view/by_line?startkey=["9","MISTRZEJOWICE"]&endkey=["9","MISTRZEJOWICE",{}]
.
.fi
.
.IP "" 0
.
.P
Zwraca wszystkie przystanki na linii \fI"9"\fR, jadącej w kierunku przystanku \fI"Mistrzejowice"\fR\.
.
.P
\fB[map] by_name\fR
.
.P
Ścieżka: \fB/_design/Stops/_view/by_name\fR
.
.br
Metoda: \fBGET\fR
.
.br
Odpowiedź: lista przystanków
.
.br
Kolejność sortowania: \fBname\fR, \fBaddress\fR
.
.P
Przykładowe użycie:
.
.IP "" 4
.
.nf

curl \-XGET http://api\.bagate\.la/kr/_design/Stops/_view/by_name?key=["Reymana","Aleja 3 maja"]
.
.fi
.
.IP "" 0
.
.P
Zwraca przystanki o nazwie \fI"Reymana"\fR i adresie \fI"Aleja 3 maja"\fR\. Uwaga: możemy otrzymać więcej niż jeden dokument, mimo że nie zdefiniowaliśmy zakresu klucza, a konkretną wartość, która w tym przypadku nie jest unikalna\.
.
.P
\fB[list] filter\fR
.
.P
Ścieżka: \fB/_design/Stops/_list/filter/<widok>\fR
.
.br
Metoda: \fBGET\fR
.
.br
Parametr: \fBwidok\fR, \fBonly\fR lub \fBexcept\fR \- lista parametrów, połączonych przecinkiem, które mają (lub których nie mają) zawierać wartości zwrócone przez funckję mapującą
.
.br
Odpowiedź: to samo co zwróci widok, z filtrowanymi wartościami
.
.P
Przykładowe użycie:
.
.IP "" 4
.
.nf

curl \-XGET http://api\.bagate\.la/kr/_design/Stops/_list/filter/by_name?except=polylines,type,updated_at&limit=1
.
.fi
.
.IP "" 0
.
.P
Zwraca jeden przystanek bez pól: \fBpolylines\fR, \fBtype\fR i \fBupdated_at\fR\.
.
.P
Zobacz scenariusze testujące \fI"_design/Stops"\fR\. \fIhttps://github\.com/Stanley/bagatela/blob/master/features/stops_design\.feature\fR
.
.SS "Wyszukiwarka"
Usługa, która pozwala na wyszukiwanie przystanków po nazwie lub lokalizacji\. Ponieważ silnikiem wyszukiwarki jest elasticsearch, pełna dokumentacja API znajduje się na stronie: \fIhttp://www\.elasticsearch\.org/guide/reference/api/search/\fR\.
.
.P
Ścieżka: \fB/_search/Stops?q=<fraza>\fR
.
.br
Metoda: \fBGET\fR
.
.br
Paramerty:
.
.IP "\(bu" 4
\fBq\fR \- fraza\. Akceptuje mi\. wieloznaczniki \fI*\fR i \fI?\fR oraz wyrażenia logiczne \fIOR\fR i \fIAND\fR\.
.
.IP "\(bu" 4
\fBsort\fR (opcjonalnie) \- sortowanie, np\.: \fI"name:asc"\fR (po nazwie, rosnąco)\. Domyślnie po trafności\.
.
.IP "\(bu" 4
\fBsize\fR (opcjonalnie) \- maksymalna liczba dokumentów spełniających kryteria zapytania\.
.
.IP "\(bu" 4
W zapytaniu możliwe są również inne opcje, wszystkie zostały opisane na: \fIhttp://www\.elasticsearch\.org/guide/reference/api/search/uri\-request\.html\fR\.
.
.IP "" 0
.
.P
Odpowiedź: lista przystanków spełniających kryteria tj\. zawierają \fIfrazę\fR w nazwie lub lokalizacji\.
.
.P
Frazę można doprecyzować, dopisując przed nią \fIname:\fR lub \fIaddress:\fR, co ograniczy wyszukiwanie do określonego pola\.
.
.P
Przykładowe użycia:
.
.IP "" 4
.
.nf

curl \-XGET http://api\.bagate\.la/kr/_search/Stops?q=baszt*
.
.fi
.
.IP "" 0
.
.P
Zwróci wszystkie przystanki, których nazwa lub lokalizacja zawiera słowo zaczynające się od: \fI"baszt"\fR\.
.
.IP "" 4
.
.nf

curl \-XGET http://api\.bagate\.la/kr/_search/Stops?q=dworzec%20AND%20location:basztowa
.
.fi
.
.IP "" 0
.
.P
Zwróci wszystkie przystanki, których nazwa lub lokalizacja zawiera słowo \fI"dworzec"\fR, a lokalizacja zawiera słowo \fI"basztowa"\fR\.
.
.P
\fBAlternatywne użycie:\fR
.
.P
Ścieżka: \fB/_search/Stops\fR
.
.br
Metoda: \fBPOST\fR
.
.br
Ładunek: Zapytanie DSL w formacie JSON
.
.P
DSL (język zapytania) jest udokumentowany na stronie: \fIhttp://www\.elasticsearch\.org/guide/reference/query\-dsl/\fR\. Ta forma pozwala formułować bardziej skomplikowane zapytania, ale wymaga znajomości języka\.
.
.P
Przykładowe użycie:
.
.IP "" 4
.
.nf

curl \-XPOST http://api\.bagate\.la/kr/_search/Stops \-d \'{
  "query": {
    "filtered" : {
      "query" : {
        "match_all" : {}
      },
      "filter" : {
        "geo_distance" : {
          "distance" : "1km",
          "location" : {
            "lat" : 50\.06551,
            "lon" : 19\.94693
          }
        }
      }
    }
  }
}\'
.
.fi
.
.IP "" 0
.
.P
Zwróci wszystkie przystanki w promieniu \fI1\fR kilometra od Dworca Głównego w Krakowie (punkt: \fI50\.06551, 19\.94693\fR)\.
.
.P
Zobacz scenariusze testujące\. \fIhttps://github\.com/Stanley/bagatela/blob/master/features/stops_search\.feature\fR
.
.SH "REPLIKACJE"
Replikacje są wykorzystywane do synchronizacji dwóch kopii tej samej bazy danych\.
.
.P
Ścieżka: \fBhttp://api\.bagate\.la/_replicate\fR
.
.br
Metoda: \fBPOST\fR
.
.br
Parametry ładunku:
.
.IP "\(bu" 4
\fBsource\fR \- \fIkod_miasta\fR czyli identyfikator bazy danych będącej źródłem danych np\.: \fI"kr"\fR\.
.
.IP "\(bu" 4
\fBtarget\fR \- baza danych do której eksportujemy dane np\.: \fI"http://user:password@rozklady\.cloudant\.com/kr"\fR\.
.
.IP "\(bu" 4
\fBcontinuous\fR (opcjonalnie) \- jeżeli \fItrue\fR replikacja będzie trwała do momentu w którym sami przerwiemy proces (wysyłając podobne zapytanie z parametrem "\fBcancel\fR"\fI:true\fR)
.
.IP "" 0
.
.P
Odpowiedź: Raport z wykonanej (lub przerwanej) replikacji\.
.
.P
Przykładowe użycie:
.
.IP "" 4
.
.nf

curl \-XPOST http://api\.bagate\.la/_replicate \-H \'Content\-Type: application/json\' \-d \'{
  "source":"dw",
  "target":"https://stanley:<password>@stanley\.cloudant\.com/dw/"
}\'
.
.fi
.
.IP "" 0
.
.SH "SCENARIUSZE TESTUJĄCE"
Aby zapewnić stabilność i niezawodność API, konieczne jest posiadanie testów funkcjonalnych\. Ponieważ są one również świetną dokumentacją, dla każdego zagadnienia dokumentacji został napisany \fIhttps://github\.com/Stanley/bagatela/tree/master/features\fR odrępny test\. Każdy z nich jest scenariuszem użycia API w czystym i zrozumiałym dla każdego języku angielskim, który jest interpretowany przez komputer za pomocą nadzędzia Cucumber \fIhttp://cukes\.info/\fR\.
