.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "BAGATELA\-GRAPH" "1" "November 2011" "Stanisław Wasiutyński" ""
.
.SH "NAME"
\fBbagatela\-graph\fR \- połączona struktura do wyszukiwania i analizy połączeń
.
.SH "WSTĘP DO API"
API (Interfejs Programowania Aplikacji) umożliwia programowy dostęp do danych (\fIwęzłów\fR, \fIpołączeń\fR, \fIprzesiadek\fR) i usług (\fIwyszukiwarka encji\fR, \fIwyszukiwarka połączeń\fR) z poziomu aplikacji trzecich\.
.
.P
API jest zgodne ze wzorcem REST \fIhttp://en\.wikipedia\.org/wiki/Representational_State_Transfer\fR\. Interakcja na zbiorach odbywa się protokołem HTTP i pozwala na wykonywanie zapytań typu GET i POST\. Dane przyjmowane i zwracane są w formacie JSON \fIhttp://json\.org\fR\.
.
.SS "Url"
Dla każdego dnia instnieje osobny graf:
.
.IP "" 4
.
.nf

http://graph\.bagate\.la/<YYYY\-MM\-DD>
.
.fi
.
.IP "" 0
.
.P
Zawiera on w sobie dane ze wszystkich miast (obsługiwanych tego dnia)\.
.
.P
\fB\fR
.
.IP "" 4
.
.nf

http://graph\.bagate\.la/demo
.
.fi
.
.IP "" 0
.
.SS "Przykłady"
Wszystkie przykłady interakcji z API korzystają z prostego narzędzia konsoli \fBcurl\fR i zostały wykonane w systemie GNU/Linux\.
.
.IP "" 4
.
.nf

$ curl http://graph\.bagate\.la \-\-verbose
* About to connect() to graph\.bagate\.la port 80 (#0)
*   Trying 31\.222\.178\.135\.\.\. connected
> GET / HTTP/1\.1
> User\-Agent: curl/7\.22\.0 (x86_64\-unknown\-linux\-gnu) libcurl/7\.22\.0 OpenSSL/1\.0\.0e zlib/1\.2\.5 libssh2/1\.3\.0
> Host: graph\.bagate\.la
> Accept: */*
>
< HTTP/1\.1 200 OK
< Server: nginx/1\.0\.9
< Date: Thu, 17 Nov 2011 18:27:44 GMT
< Content\-Type: application/json;charset=UTF\-8
< Transfer\-Encoding: chunked
< Connection: keep\-alive
< Access\-Control\-Allow\-Origin: *
<
* Connection #0 to host graph\.bagate\.la left intact
* Closing connection #0
{"version":"0\.7\-SNAPSHOT","name":"Rexster: A Graph Server","graphs":["demo"],"queryTime":0\.138796,"upTime":"0[d]:00[h]:03[m]:40[s]"}
.
.fi
.
.IP "" 0
.
.SS "Kontrybucja"
(również do dokumentacji) jest mile widziana! Weź \fIhttps://github\.com/Stanley/bagatela\fR na widły i poproś o akceptacje zmian\.
.
.SH "ZAPYTANIA O DANE"
Interfejs programistyczny jest oparty o serwer Rexster \fIhttp://rexster\.tinkerpop\.com\fR, który udostępnia dane przechowywane w bazie danych OrientDB \fIhttp://www\.orientechnologies\.com/\fR\. Jego szczegóły opisano w dokumentacji Rexster REST API \fIhttps://github\.com/tinkerpop/rexster/wiki/Basic\-REST\-API\fR\.
.
.SS "Zasoby"
Graf składa się wyłącznie z wierzchołków i skierowanych relacji między nimi, zwanych krawędziami\. Dalszy podział tych zasobów na klasy jest umowny, gdyż ich atrybuty nie są ograniczone żadną strukturą\. OrientDB organizuje dane w tzw\. klastrach \fIhttp://code\.google\.com/p/orient/wiki/Concepts#Cluster\fR, które są przypisane do każdej klasy\.
.
.SS "Odkrywalność"
Graf jest strukturą połączoną, co znaczy że dane które on zawiera, są od siebie zależne\. Naturalną konsekwencją tego jest API, które zwraca te zależności w postaci linków, czyli adresów URI, zawsze tam gdzie ma to sens\. Zaleca się w ten sposób "odkrywać" graf, zamiast polegać na dokumentacji, gdyż uchroni nas to przez możliwymi zmianami API w przyszłości\. Odkrywanie najlepiej zacząć od korzenia:
.
.P
Ścieżka: \fB/\fR
.
.br
Metoda: \fBGET\fR
.
.br
Odpowiedź: \fI200\fR \- referencje do najważniejszych zasobów\. \fI404\fR \- graf nie istnieje (brak danych z danego dnia lub zły format daty)\.
.
.P
Przykładowe użycie:
.
.IP "" 4
.
.nf

$ curl http://graph\.bagate\.la/demo/
{"version":"0\.7\-SNAPSHOT","name":"demo","graph":"readonlyindexablegraph[orientgraph[local:\e/home\e/orientdb\e/demo]]","readOnly":true,"type":"com\.tinkerpop\.blueprints\.pgm\.impls\.orientdb\.OrientGraph","queryTime":2\.618832,"upTime":"0[d]:00[h]:04[m]:51[s]","extensions":[{"title":"evaluate an ad\-hoc Gremlin script for a graph\.","method":"GET","href":"tp\e/gremlin"},{"title":"evaluate an ad\-hoc Gremlin script for a graph\.","method":"POST","href":"tp\e/gremlin"}]}
.
.fi
.
.IP "" 0
.
.SS "Archiwa"
W dowolnej chwili dostępne są grafy dla dnia bieżącego oraz siedmiu następnych\. Dane historyczne są archiwizowane i dostępne jedynie w następujący sposób:
.
.P
Ścieżka: \fB\.gz\fR
.
.br
Metoda: \fBGET\fR
.
.br
Odpowiedź: \fI200\fR \- zarchiwizowana baza danych\. \fI404\fR \- graf nie istnieje (brak danych z danego dnia lub zły format daty)\.
.
.P
Przykładowe użycie:
.
.IP "" 4
.
.nf

$ cd <ścieżka do orientdb>
$ wget http://graph\.bagate\.la/2011\-08\-18\.gz
$ \./bin/console\.sh
OrientDB console v\.1\.0rc6 (build @BUILD@) www\.orientechnologies\.com
Type \'help\' to display all the commands supported\.\'

> create database local:/tmp/bagatela admin admin local
Creating database [local:/tmp/bagatela] using the storage type [local]\.\.\.
Database created successfully\.

Current database is: local:/tmp/bagatela

> import database 2011\-08\-18\.gz
Importing database from file 2011\-08\-18\.gz\.\.\.
.
.fi
.
.IP "" 0
.
.P
Dane mogą zostać wykorzystane np\. do stworzenia lokalnej instancji bazy danych OrientDB, wizualizacji grafu, analizy itp\.
.
.SH "WĘZEŁ"
Wierzchołek w grafie\. Reprezentuje punkt na mapie\. Węzły są tworzone na podstawie przystanków \fIAPI\.1\.html#PRZYSTANEK\fR\.
.
.P
Ścieżka: \fB/vertices/<id>\fR
.
.br
Metoda: \fBGET\fR
.
.br
Parametry: \fBid\fR \- identyfikator węzła\.
.
.br
Odpowiedź: \fI200\fR \- wartości atrybutów i referencje do relacji węzła\. \fI404\fR \- węzeł nie istnieje\.
.
.P
Przykładowe użycie:
.
.IP "" 4
.
.nf

$ curl http://graph\.bagate\.la/demo/vertices/7:77
{"version":"0\.7\-SNAPSHOT","results":{"lon":19\.93278833333333,"name":"Teatr Bagatela","lat":50\.06352999999999,"_id":"#7:77","_type":"vertex"},"queryTime":1\.458626}
.
.fi
.
.IP "" 0
.
.SS "Atrybuty"
.
.IP "\(bu" 4
\fB_id\fR \- unikalny identyfikator w formie: \fI"#<cluser>:<position>"\fR\. Np\. \fI"#8:16"\fR
.
.IP "\(bu" 4
\fB_type\fR \- zawsze \fI"vertex"\fR\.
.
.IP "\(bu" 4
\fBlat\fR \- szerokość geograficzna\. Np\.: \fI50\.123\fR\.
.
.IP "\(bu" 4
\fBlon\fR \- długość geograficzna\. Np\.: \fI19\.987\fR\.
.
.IP "\(bu" 4
\fBsource\fR \- adres URI do dokumentu, na podstawie którego został utworzony ten węzeł (istnieje tylko dla klasy \fI"Stop"\fR)\. Np\.: \fI"http://api\.bagate\.la/kr/abc?rev=def"\fR\.
.
.IP "" 0
.
.P
W sytuacji, gdy nie mamy wiedzy o tym który dokładnie przystanek każdy rozkład jazdy reprezentuje (brak wartości \fBstop_id\fR w dokumencie \fITimetable\fR \fIAPI\.1\.html#ROZK\-AD\-JAZDY\fR), zbiór przystanków o tej samej nazwie, będzie reprezentowany na grafie tylko przez jeden węzeł klasy \fIHub\fR\. Sprawi to, że nie pojawią się relacje przesiadek, dlatego przy trawersacji nie będziemy w stanie stwierdzić czy nastąpiło przejście z jednego przystanku do drugiego o tej samej nazwie\. Klasa \fIStop\fR reprezentuje fizyczny przystanek (wiata albo słupek)\.
.
.SH "POŁĄCZENIE"
Relacja między dwoma węzłami\. Zachodzi gdy istnieje przynajmniej jedna linia, która kursuje między nimi bezpośrednio (np\. linia jeżdżąca po przystankach \fIA\fR &rarr; \fIB\fR &rarr; \fIC\fR, składa się z dokładnie dwóch połączeń: \fIA\fR do \fIB\fR i \fIB\fR do \fIC\fR)\.
.
.P
Ścieżka: \fB/vertices/<id>/<dir>E?_label=connects\fR
.
.br
Metoda: \fBGET\fR
.
.br
Parametry: \fBid\fR \- identyfikator węzła, \fBdir\fR \- kierunek relacji\. Może być \fIin\fR, \fIout\fR lub \fIboth\fR\.
.
.br
Odpowiedź: \fI200\fR \- połączenia (przychodzące, wychodzące lub wszystkie) z węzła \fBid\fR\.
.
.P
Przykładowe użycie:
.
.IP "" 4
.
.nf

$ curl http://graph\.bagate\.la/2011\-11\-10/vertices/31/outE?_label=connects
.
.fi
.
.IP "" 0
.
.SS "Atrybuty"
.
.IP "\(bu" 4
\fB_id\fR \- unikalny identyfikator w formie: \fI"#\fIcluser\fR:\fIposition\fR"\fR\. Np\. \fI"#9:10"\fR
.
.IP "\(bu" 4
\fB_inV\fR \- indentyfikator węzła wejściowego\.
.
.IP "\(bu" 4
\fB_label\fR \- zawsze \fI"connects"\fR\.
.
.IP "\(bu" 4
\fB_outE\fR \- indentyfikator węzła wyjściowego\.
.
.IP "\(bu" 4
\fB_type\fR \- zawsze \fI"edge"\fR\.
.
.IP "\(bu" 4
\fBrides\fR \- lista kursów wszystkich linii na danej krawędzi\. Atrybut typu tablicy asocjacyjnej\. Przechowuje pary, w których godzinie odjazdu (w formacie liczby minut od północy; np\. dla \fI"12:00"\fR jest to \fI"720"\fR) odpowiada tablica z informacjami o połączeniu (patrz niżej)\.
.
.IP "\(bu" 4
\fBlength\fR \- długość odcinka w metrach\. Liczona wzdłuż trasy (jeżeli ta jest zdefiniowana w polu \fBpolylines\fR przystanku \fIAPI\.1\.html#PRZYSTANEK\fR początkowego), lub po linii prostej\.
.
.IP "" 0
.
.SS "Informacje o połączeniu"
Obiekt typu tablicy asocjacyjnej, zawierającej następujące pary:
.
.IP "\(bu" 4
\fBline\fR \- numer linii\. Np\. \fI"4"\fR\.
.
.IP "\(bu" 4
\fBduration\fR \- czas podróży w minutach\. Np\. \fI2\fR\.
.
.IP "" 0
.
.SH "PRZESIADKA"
Relacja między dwoma węzłami klasy \fIStop\fR\. Jeżeli istnieje relacja z węzła \fIA\fR do \fIB\fR to istnieje też druga, inna relacja z węzła \fIB\fR do \fIA\fR\.
.
.P
Ścieżka: \fB/vertices/<id>/<dir>E?_label=transfers\fR
.
.br
Metoda: \fBGET\fR
.
.br
Parametry: \fBid\fR \- identyfikator węzła, \fBdir\fR \- kierunek relacji\. Może być \fIin\fR, \fIout\fR lub \fIboth\fR\.
.
.br
Odpowiedź: \fI200\fR \- przesiadki (do, z lub wszystkie) z węzła \fB<id>\fR\.
.
.SS "Atrybuty"
.
.IP "\(bu" 4
\fB_id\fR \- unikalny identyfikator w formie: \fI"#\fIcluser\fR:\fIposition\fR"\fR\. Np\. \fI"#10:1"\fR
.
.IP "\(bu" 4
\fB_inV\fR \- indentyfikator węzła wejściowego\.
.
.IP "\(bu" 4
\fB_label\fR \- zawsze \fI"transfers"\fR\.
.
.IP "\(bu" 4
\fB_outE\fR \- indentyfikator węzła wyjściowego\.
.
.IP "\(bu" 4
\fB_type\fR \- zawsze \fI"edge"\fR\.
.
.IP "\(bu" 4
\fBpenatly\fR \- orientacyjny czas w minutach, potrzeby do przemieszczenia się z jednego węzła do drugiego\. Np\.: \fI1\fR\.
.
.IP "" 0
.
.SH "WYSZUKIWARKA"
Usługa, która pozwala na wyszukiwanie węzłów i relacji według dowolnych kryteriów\. Zwrócony element często jest jedynie zalążkiem do wyszukiwania ścieżek i innych struktur powstających w procesie \fItrawersacji grafu\fR\. Ponieważ silnikiem wyszukiwarki jest elasticsearch, pełna dokumentacja API znajduje się na stronie: \fIhttp://www\.elasticsearch\.org/guide/reference/api/search/\fR\.
.
.P
Ścieżka: \fB/search?q=<fraza>\fR
.
.br
Metoda: \fBGET\fR
.
.br
Paramerty:
.
.IP "\(bu" 4
\fBq\fR \- fraza\. Akceptuje mi\. wieloznaczniki \fI*\fR i \fI?\fR oraz wyrażenia logiczne \fIOR\fR i \fIAND\fR\.
.
.IP "\(bu" 4
\fBsort\fR (opcjonalnie) \- sortowanie, np\.: \fI"name:asc"\fR (po nazwie, rosnąco)\. Domyślnie po trafności\.
.
.IP "\(bu" 4
\fBsize\fR (opcjonalnie) \- maksymalna liczba dokumentów spełniających kryteria zapytania\.
.
.IP "\(bu" 4
W zapytaniu możliwe są również inne opcje, wszystkie zostały opisane na: \fIhttp://www\.elasticsearch\.org/guide/reference/api/search/uri\-request\.html\fR\.
.
.IP "" 0
.
.P
Odpowiedź: lista węzłów spełniających kryteria tj\. zawierają \fIfrazę\fR w nazwie lub lokalizacji\.
.
.P
Frazę można doprecyzować, dopisując przed nią \fIname:\fR lub \fIaddress:\fR, co ograniczy wyszukiwanie do określonego pola\.
.
.P
\fBAlternatywne użycie:\fR
.
.P
Ścieżka: \fB/search\fR
.
.br
Metoda: \fBPOST\fR
.
.br
Ładunek: Zapytanie DSL w formacie JSON
.
.P
DSL (język zapytania) jest udokumentowany na stronie: \fIhttp://www\.elasticsearch\.org/guide/reference/query\-dsl/\fR\. Ta forma pozwala formułować bardziej skomplikowane zapytania, ale wymaga znajomości języka\.
.
.SH "TRAWERSACJA GRAFU"
Przechodzenie grafu w zdefiniowany sposób\. Zaczynamy zawsze od jednego wierzchołka (lub krawędzi), a następnie, po jego krawędziach (lub jej wierzchołkach), odwiedzamy kolejne encje (wiele w tym samym czasie)\. Celem tego procesu może być uzyskanie np\.: węzłów, krawędzi lub obu tych typów, odwiedzonych w procesie trawersacji\.
.
.P
Do definicji sposobu przechodzenia grafu służy Gremlin \fIhttp://gremlin\.tinkerpop\.com/\fR, będący rozszerzeniem języka Groovy \fIhttp://groovy\.codehaus\.org/\fR\. Pozwala on na wykonywanie szeregu operacji ad\-hoc na grafie\.
.
.P
Ścieżka: \fB/tp/gremlin\fR
.
.br
Metoda: \fBPOST\fR
.
.br
Parametry:
.
.IP "\(bu" 4
\fBrexster\.showTypes\fR \- displays the properties of the elements with their native data type (default is false),
.
.IP "\(bu" 4
\fBrexster\.returnKeys\fR \- the element property keys to return (default is to return all element properties),
.
.IP "\(bu" 4
\fBrexster\.offset\.start\fR \- start index for a paged set of data to be returned,
.
.IP "\(bu" 4
\fBrexster\.offset\.end\fR \- end index for a paged set of data to be returned
.
.IP "\(bu" 4
\fBscript\fR \- the Gremlin script to be evaluated
.
.IP "" 0
.
.P
Odpowiedź: \fI200\fR \- węzły, krawędzie, ścieżka (identyfikatory węzłów i krawędzi) lub pełna ścieżka wraz z atrybutami węzłów i krawędzi\. \fI404\fR \- węzeł \fBid\fR nie istnieje\.
.
.SH "POŁĄCZENIA KOMUNIKACYJNE"
Połączenie komunikacyjne jest ścieżką, która składa się z węzłów, połączonych konkretnym odjazdem (lub przesiadką)\. W przeciwieństwie do zwykłej trawersacji, nie jest to lista wszystkich kursów (odjazdów) w danym połączeniu\. Ponieważ wynik jest związany z czasem, zarówno kursy jak i węzły mogą zależeć od czasu, będącym jednym z parametrów tego zapytania\.
.
.P
Ścieżka: \fIjuż wkrótce\fR
.
.br
Metoda: \fBPOST\fR
.
.br
Parametry: \fBid\fR \- identyfikator węzła początkowego\.
.
.br
Parametry ładunku:
.
.IP "\(bu" 4
\fBstart_at\fR \- czas odjazdu z węzła początkowego (nie wcześniej niż \fBstart_at\fR)\.
.
.IP "\(bu" 4
\fBfinish_at\fR \- czas przejazdu na węzeł docelowy (nie później niż \fBfinish_at\fR)\. Jeżeli parametr \fBstart_at\fR jest zdefiniowany, \fBfinish_at\fR zostanie zignorowany\.
.
.IP "\(bu" 4
\fBtime_limit\fR \- limit czasu trwania połączenia w minutach\. Domyślnie \fI120\fR\.
.
.IP "\(bu" 4
\fBto\fR \- węzeł docelowy\.
.
.IP "" 0
.
.P
Odpowiedź: \fI200\fR \- teoretycznie (zgodnie z algorytmem A* \fIhttp://en\.wikipedia\.org/wiki/A*_search_algorithm\fR) najszybsze czasowo połączenie komunikacyjne, pomiędzy dwoma wierzchołkami grafu\.
